name: aeMeta

channels:
  - conda-forge
  - bioconda

dependencies:
  # core packages for workflow
  - nextflow
  - bowtie2
  - samtools
  - r-base
  - r-data.table
  - fastp
  - krakenuniq
  - fastqc>=0.12.1
  - pmdtools
  - multiqc
